### ISSUE TITLE
Can not deploy omiga!!!!!!!!!4.05this is ok but today is error

### ISSUE THREAD

**Issue by doxulovezh** [nervosnetwork/ckb-explorer#1752]
**Environment**

- **Operating system**: Linux  / Windows
- **Arch**: x64
- **Installation**: GitHub Release

**Describe the bug**
Code:https://github.com/omiga-core/ckb-omiga/blob/master/example/secp256k1/1-deploy.ts

inscription id:  0xef876fd2769a448df6f1e0278ff0fe1606cc5a62a8d6c15bc976a8ed16ab862e
{"version":"0x0","cellDeps":[{"outPoint":{"txHash":"0x71a7ba8fc96349fea0ed3a5c47992e3b4084b031a42264a018e0072e8172e46c","index":"0x0"},"depType":"depGroup"},{"outPoint":{"txHash":"0x1ae1ba691d00525c17b262126576ca5d41b9c6bc09e94038ec26570d0b3f0219","index":"0x0"},"depType":"code"}],"headerDeps":[],"inputs":[{"previousOutput":{"txHash":"0xa685957344a4a69c9569a63240ca59b9d78c7047b821a1c958a5aaf14731beaa","index":"0x1"},"since":"0x0"}],"outputs":[{"capacity":"0x4fb8a1600","lock":{"codeHash":"0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8","hashType":"type","args":"0x10f4f9d4fc9e46a63a158aa26d9b0e8fcdac7047"},"type":{"codeHash":"0x5c33fc69bd72e895a63176147c6ab0bb5758d1c7a32e0914f99f9ec1bed90d41","hashType":"type","args":"0xef876fd2769a448df6f1e0278ff0fe1606cc5a62a8d6c15bc976a8ed16ab862e"}},{"capacity":"0x2245cce2a","lock":{"codeHash":"0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8","hashType":"type","args":"0x10f4f9d4fc9e46a63a158aa26d9b0e8fcdac7047"}}],"outputsData":["0x080d746573742050726f746f636f6c0774657374524742dff01f7f1f37e504421199030cb6d6f6ab69b5ee4e946545d34d4df2de7447c90040075af0750700000000000000000000e8764817000000000000000000000000","0x"],"witnesses":["0x5500000010000000550000005500000041000000219bb9dba74f16af53ddcfc0e9674f2f15b4c4608f0fec1a8b290ecef93f37fe6bcbac8cd3d0ed1b7c1d7e141617547a32eea759584a0106fa07b9503ce3090500","0x"]}
ResponseException [Error]: {"code":-301,"message":"TransactionFailedToResolve: Resolve failed Unknown(OutPoint(0x1ae1ba691d00525c17b262126576ca5d41b9c6bc09e94038ec26570d0b3f021900000000))","data":"Resolve(Unknown(OutPoint(0x1ae1ba691d00525c17b262126576ca5d41b9c6bc09e94038ec26570d0b3f021900000000)))"}
    at D:\2024\RGB++\ckb-omiga\node_modules\@nervosnetwork\ckb-sdk-rpc\src\method.ts:43:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deploy (D:\2024\RGB++\ckb-omiga\example\secp256k1\1-deploy.ts:56:16) {
  code: 204
}

**Comment by doxulovezh** [comment]
this is mainnet  ,but testnet id error too

**Comment by Keith-CY** [comment]
Hi @doxulovezh 

The error message 

```
TransactionFailedToResolve: Resolve failed Unknown(OutPoint(0x1ae1ba691d00525c17b262126576ca5d41b9c6bc09e94038ec26570d0b3f021900000000))"
```

means that a live cell pointed by `0x1ae1ba691d00525c17b262126576ca5d41b9c6bc09e94038ec26570d0b3f021900000000` cannot be found.

The pointer `0x1ae1ba691d00525c17b262126576ca5d41b9c6bc09e94038ec26570d0b3f0219 00000000` can be treated as 

```
tx hash: 0x1ae1ba691d00525c17b262126576ca5d41b9c6bc09e94038ec26570d0b3f0219
output index: 0x00000000
```

and its cell can be found at https://explorer.nervos.org/transaction/0x1ae1ba691d00525c17b262126576ca5d41b9c6bc09e94038ec26570d0b3f0219

The cell had been used on 2024/1/19, so it cannot be found in the live cells and leads to the `Resolve failed Unknown OutPoint` error

**Comment by doxulovezh** [comment]
How did I create a cell of the same type? Please help me, thank you

**Comment by doxulovezh** [comment]
![image](https://github.com/nervosnetwork/ckb-explorer/assets/54633419/ccf8a5ee-6668-4480-8e73-e2ae16d723aa)
Some information in the appropriate SDK

**Comment by doxulovezh** [comment]
this is mainnet
![image](https://github.com/nervosnetwork/ckb-explorer/assets/54633419/4d8d96e6-8860-4c4c-8a82-39983313db01)

**Comment by Keith-CY** [comment]
> this is mainnet ![image](https://private-user-images.githubusercontent.com/54633419/320247114-4d8d96e6-8860-4c4c-8a82-39983313db01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NTU5OTAsIm5iZiI6MTcxMjQ1NTY5MCwicGF0aCI6Ii81NDYzMzQxOS8zMjAyNDcxMTQtNGQ4ZDk2ZTYtODg2MC00YzRjLThhODItMzk5ODMzMTNkYjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDAyMDgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMmRhODI2MzRlNTU4YzAwMzVmYzhjNmUxNTU4MTQ2ZjhmMmJkMWJiNjI5Y2QwNjM2ODkzZjdmMmRjMzc1OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.13BYDpGKRy-judPCRpI5jOr3zfhwF4AnbI28DTyATOc)

Got it, replace txHash in

<img width="770" alt="image" src="https://github.com/nervosnetwork/ckb-explorer/assets/7271329/9e83430a-5527-483f-8e49-d51de0a13b8d">

with `0x159a173da44a5bb698c44b6c30b46dd446bc8f3f1930e87aa4debe56d7674f8a`

as mentioned above, the `outPoint` at

```
tx hash: 0x1ae1ba691d00525c17b262126576ca5d41b9c6bc09e94038ec26570d0b3f0219
index: 0x0
```
has been used in https://explorer.nervos.org/transaction/0x1ae1ba691d00525c17b262126576ca5d41b9c6bc09e94038ec26570d0b3f0219

and now it's at

```
tx hash: 0x159a173da44a5bb698c44b6c30b46dd446bc8f3f1930e87aa4debe56d7674f8a
index: 0x0
```

**Comment by doxulovezh** [comment]
0x159a173da44a5bb698c44b6c30b46dd446bc8f3f1930e87aa4debe56d7674f8a    Can I only use my own address? Can I use other addresses
![image](https://github.com/nervosnetwork/ckb-explorer/assets/54633419/5fcc2480-3bc8-4552-8724-89533bdcad04)
![image](https://github.com/nervosnetwork/ckb-explorer/assets/54633419/6c54a974-3eb5-45ac-8528-dbbee22f8233)

**Comment by doxulovezh** [comment]
this is my address:
ckb1qyqppa8e6n7fu34x8g2c4gndnv8glndvwprs63l794

**Comment by Keith-CY** [comment]
> 0x159a173da44a5bb698c44b6c30b46dd446bc8f3f1930e87aa4debe56d7674f8a Can I only use my own address? Can I use other addresses ![image](https://private-user-images.githubusercontent.com/54633419/320247548-5fcc2480-3bc8-4552-8724-89533bdcad04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NTY3NjQsIm5iZiI6MTcxMjQ1NjQ2NCwicGF0aCI6Ii81NDYzMzQxOS8zMjAyNDc1NDgtNWZjYzI0ODAtM2JjOC00NTUyLTg3MjQtODk1MzNiZGNhZDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDAyMjEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzZDZjNDJmOTViNjA4MmQyYzNmMWVlMmJlOTUzZTI5NzVjYmFkMmJhZmYzYzg5MDlmZmI5NmVlZjIxNmU2MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zyy2X1mNwqSBhwPL7n1Z_z1mJBTU-W-NNUXg3JanyoU) ![image](https://private-user-images.githubusercontent.com/54633419/320247605-6c54a974-3eb5-45ac-8528-dbbee22f8233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NTY3NjQsIm5iZiI6MTcxMjQ1NjQ2NCwicGF0aCI6Ii81NDYzMzQxOS8zMjAyNDc2MDUtNmM1NGE5NzQtM2ViNS00NWFjLTg1MjgtZGJiZWUyMmY4MjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDAyMjEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZjFiNDZkOTI2MmE4YWM5OGIxMDA3MjJjMzgzNWI2MjU3NjkzMTAzNTlhNjdhMGYxMmNmN2IxMTVlZTU5Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qHTmHcLjBWEbU0cEqAIZAOyS39ZasN3Mlf-DzIlIb9k)

You have to deploy your own `Inscription Info Script` if you want to refer to the one under your control.

But I don't understand why `TransactionFailedVerify` error was thrown because `Inscription Info Script` won't lead to it.

Could you share your transaction here?

**Comment by doxulovezh** [comment]
how to deploy your own Inscription Info Script?

**Comment by doxulovezh** [comment]
> > 0x159a173da44a5bb698c44b6c30b46dd446bc8f3f1930e87aa4debe56d7674f8a Can I only use my own address? Can I use other addresses ![image](https://private-user-images.githubusercontent.com/54633419/320247548-5fcc2480-3bc8-4552-8724-89533bdcad04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NTY3NjQsIm5iZiI6MTcxMjQ1NjQ2NCwicGF0aCI6Ii81NDYzMzQxOS8zMjAyNDc1NDgtNWZjYzI0ODAtM2JjOC00NTUyLTg3MjQtODk1MzNiZGNhZDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDAyMjEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzZDZjNDJmOTViNjA4MmQyYzNmMWVlMmJlOTUzZTI5NzVjYmFkMmJhZmYzYzg5MDlmZmI5NmVlZjIxNmU2MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zyy2X1mNwqSBhwPL7n1Z_z1mJBTU-W-NNUXg3JanyoU) ![image](https://private-user-images.githubusercontent.com/54633419/320247605-6c54a974-3eb5-45ac-8528-dbbee22f8233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NTY3NjQsIm5iZiI6MTcxMjQ1NjQ2NCwicGF0aCI6Ii81NDYzMzQxOS8zMjAyNDc2MDUtNmM1NGE5NzQtM2ViNS00NWFjLTg1MjgtZGJiZWUyMmY4MjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDAyMjEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZjFiNDZkOTI2MmE4YWM5OGIxMDA3MjJjMzgzNWI2MjU3NjkzMTAzNTlhNjdhMGYxMmNmN2IxMTVlZTU5Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qHTmHcLjBWEbU0cEqAIZAOyS39ZasN3Mlf-DzIlIb9k)
> 
> You have to deploy your own `Inscription Info Script` if you want to refer to the one under your control.
> 
> But I don't understand why `TransactionFailedVerify` error was thrown because `Inscription Info Script` won't lead to it.
> 
> Could you share your transaction here?

 Inscription Info Script is not deploy by me

**Comment by Keith-CY** [comment]
> > > 0x159a173da44a5bb698c44b6c30b46dd446bc8f3f1930e87aa4debe56d7674f8a Can I only use my own address? Can I use other addresses ![image](https://private-user-images.githubusercontent.com/54633419/320247548-5fcc2480-3bc8-4552-8724-89533bdcad04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NTY3NjQsIm5iZiI6MTcxMjQ1NjQ2NCwicGF0aCI6Ii81NDYzMzQxOS8zMjAyNDc1NDgtNWZjYzI0ODAtM2JjOC00NTUyLTg3MjQtODk1MzNiZGNhZDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDAyMjEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzZDZjNDJmOTViNjA4MmQyYzNmMWVlMmJlOTUzZTI5NzVjYmFkMmJhZmYzYzg5MDlmZmI5NmVlZjIxNmU2MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zyy2X1mNwqSBhwPL7n1Z_z1mJBTU-W-NNUXg3JanyoU) ![image](https://private-user-images.githubusercontent.com/54633419/320247605-6c54a974-3eb5-45ac-8528-dbbee22f8233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NTY3NjQsIm5iZiI6MTcxMjQ1NjQ2NCwicGF0aCI6Ii81NDYzMzQxOS8zMjAyNDc2MDUtNmM1NGE5NzQtM2ViNS00NWFjLTg1MjgtZGJiZWUyMmY4MjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDAyMjEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZjFiNDZkOTI2MmE4YWM5OGIxMDA3MjJjMzgzNWI2MjU3NjkzMTAzNTlhNjdhMGYxMmNmN2IxMTVlZTU5Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qHTmHcLjBWEbU0cEqAIZAOyS39ZasN3Mlf-DzIlIb9k)
> > 
> > 
> > You have to deploy your own `Inscription Info Script` if you want to refer to the one under your control.
> > But I don't understand why `TransactionFailedVerify` error was thrown because `Inscription Info Script` won't lead to it.
> > Could you share your transaction here?
> 
> Inscription Info Script is not deploy by me

Usually, we will reuse a deployed contract/script, this is a typical difference from EVM.

Contract/script on CKB is a binary in a cell, and can be thought of as a linkable library in our computer system(or a globally installed NPM dependency that can be imported into any project)

But it's fine to deploy your own `Inscription Info Script`, the standard steps are as follows

1. Write your own contract/script, and compile it into binary. The source code of `Inscription Info Script` is required, you may ask for it in `Omiga`'s repo because I didn't find an open-source one.
2. Store the binary in your live cell by a transaction, just as https://explorer.nervos.org/transaction/0x159a173da44a5bb698c44b6c30b46dd446bc8f3f1930e87aa4debe56d7674f8a did. Check the data field of outputs[0], binary is there
<img width="2840" alt="image" src="https://github.com/nervosnetwork/ckb-explorer/assets/7271329/5799ce85-8ab7-4fe2-abce-0f7c0f2b47de">
Deploying a script is simply storing script binary in a cell, specifically, storing the binary in cell's `output_data` field.

You can download the transaction and check the `output_data[0]` field

<img width="1011" alt="image" src="https://github.com/nervosnetwork/ckb-explorer/assets/7271329/c772a39d-b879-40c1-9f92-f099ac663518">






Ref:
Deploy a script: https://docs.nervos.org/docs/labs/sudtbycapsule/#deploy
