### ISSUE TITLE
Failed to run in supervisor

### ISSUE THREAD

**Issue by wo4zhuzi** [nervosnetwork/ckb-explorer#709]
The command line startup was successful, but the following error occurred when starting in the supervisor

```
/var/lib/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:5:in `expand_path': couldn't find login name -- expanding `~' (ArgumentError)
        from /var/lib/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:5:in `<class:Pry>'
        from /var/lib/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:1:in `<main>'
        from /var/lib/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /var/lib/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /var/lib/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /var/lib/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /var/lib/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /var/lib/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
        from /var/lib/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
        from /var/lib/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
        from /var/lib/gems/2.6.0/gems/pry-0.12.2/lib/pry.rb:119:in `<main>'
        from /var/lib/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /var/lib/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /var/lib/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /var/lib/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /var/lib/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /var/lib/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
        from /var/lib/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
        from /var/lib/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
        from /var/lib/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
        from /var/lib/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
        from /var/lib/gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
        from /root/tool/ckb/ckb-explorer/config/application.rb:20:in `<top (required)>'
        from /root/tool/ckb/ckb-explorer/config/environment.rb:2:in `require_relative'
        from /root/tool/ckb/ckb-explorer/config/environment.rb:2:in `<top (required)>'
        from /root/tool/ckb/ckb-explorer/lib/ckb_block_node_processor.rb:1:in `require_relative'
        from /root/tool/ckb/ckb-explorer/lib/ckb_block_node_processor.rb:1:in `<main>'
```

How to solve this problem?

**Comment by shaojunda** [comment]
Can you give me more information? such as:
1. Operating system
2. Which commands were executed
3. supervisor related config

**Comment by wo4zhuzi** [comment]
> Can you give me more information? such as:
> 
> 1. Operating system
> 2. Which commands were executed
> 3. supervisor related config

1、系统是 Ubuntu 18.04.4 LTS 
2、执行命令 `ruby lib/ckb_block_node_processor.rb`
直接在命令行是可以执行成功的,但是运行一会总是自己断开。

断开时错误码 :

```
/usr/lib/ruby/2.6.0/net/protocol.rb:217:in `rbuf_fill': too many connection resets 
(due to Net::ReadTimeout with #<TCPSocket:
(closed)> - Net::ReadTimeout) after 2583 requests on 46919926379660,
last used 3.00347333 seconds ago (Net::HTTP::Persistent::Error)
```
所以放在supervisor中运行。

3、supervisor 配置文件

```
[program:ckb_explorer]
command     = /bin/bash -c 'source "$0" && exec "$@"' /etc/profile ruby  /root/tool/ckb/ckb-explorer/lib/ckb_block_node_processor.rb
directory   = /root/tool/ckb/ckb-explorer/
user        = root
startsecs   = 3
autorestart = true

redirect_stderr         = true
stdout_logfile_maxbytes = 50MB
stdout_logfile_backups  = 10
stdout_logfile          = /srv/log/ckb_explorer.log
```
运行报错：

```
/var/lib/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:5:in `expand_path': couldn't find login name -- expanding `~' (ArgumentError)
        from /var/lib/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:5:in `<class:Pry>'
        from /var/lib/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:1:in `<main>'
        from /var/lib/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /var/lib/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /var/lib/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /var/lib/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /var/lib/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /var/lib/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
        from /var/lib/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
        from /var/lib/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
        from /var/lib/gems/2.6.0/gems/pry-0.12.2/lib/pry.rb:119:in `<main>'
        from /var/lib/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /var/lib/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /var/lib/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /var/lib/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /var/lib/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /var/lib/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
        from /var/lib/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
        from /var/lib/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
        from /var/lib/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
        from /var/lib/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
        from /var/lib/gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
        from /root/tool/ckb/ckb-explorer/config/application.rb:20:in `<top (required)>'
        from /root/tool/ckb/ckb-explorer/config/environment.rb:2:in `require_relative'
        from /root/tool/ckb/ckb-explorer/config/environment.rb:2:in `<top (required)>'
        from /root/tool/ckb/ckb-explorer/lib/ckb_block_node_processor.rb:1:in `require_relative'
        from /root/tool/ckb/ckb-explorer/lib/ckb_block_node_processor.rb:1:in `<main>'
```

**Comment by shaojunda** [comment]
Which branch are you using？

**Comment by wo4zhuzi** [comment]
> Which branch or release are you using？

v0.10.1

**Comment by shaojunda** [comment]
> 2、执行命令 ruby lib/ckb_block_node_processor.rb
直接在命令行是可以执行成功的,但是运行一会总是自己断开。

Can you connect to the node stably?

```
(due to Net::ReadTimeout with #<TCPSocket:
(closed)> - Net::ReadTimeout) after 2583 requests on 46919926379660,
last used 3.00347333 seconds ago (Net::HTTP::Persistent::Error)
```

this error looks like the link timed out.

**Comment by wo4zhuzi** [comment]
> > 2、执行命令 ruby lib/ckb_block_node_processor.rb
> > 直接在命令行是可以执行成功的,但是运行一会总是自己断开。
> 
> Can you connect to the node stably?
> 
> ```
> (due to Net::ReadTimeout with #<TCPSocket:
> (closed)> - Net::ReadTimeout) after 2583 requests on 46919926379660,
> last used 3.00347333 seconds ago (Net::HTTP::Persistent::Error)
> ```
> 
> this error looks like the link timed out.

I think the node link is normal, and the database is also inserted normally. This is the log

![image](https://user-images.githubusercontent.com/20334885/88761807-79683100-d1a2-11ea-95be-92d62433e664.png)

**Comment by shaojunda** [comment]
> > > 2、执行命令 ruby lib/ckb_block_node_processor.rb
> > > 直接在命令行是可以执行成功的,但是运行一会总是自己断开。
> > 
> > 
> > Can you connect to the node stably?
> > ```
> > (due to Net::ReadTimeout with #<TCPSocket:
> > (closed)> - Net::ReadTimeout) after 2583 requests on 46919926379660,
> > last used 3.00347333 seconds ago (Net::HTTP::Persistent::Error)
> > ```
> > 
> > 
> > this error looks like the link timed out.
> 
> I think the node link is normal, and the database is also inserted normally. This is the log
> 
> ![image](https://user-images.githubusercontent.com/20334885/88761807-79683100-d1a2-11ea-95be-92d62433e664.png)
> 
> After a while, deploy the node to the same server and observe whether the problem will reappear

ok

**Comment by wo4zhuzi** [comment]
> > > > 2，执行命令ruby lib / ckb_block_node_processor.rb直接
> > > > 在命令行是可以执行成功的，但是运行一会总是自己替换。
> > > 
> > > 
> > > 您能否稳定地连接到节点？
> > > ```
> > > (due to Net::ReadTimeout with #<TCPSocket:
> > > (closed)> - Net::ReadTimeout) after 2583 requests on 46919926379660,
> > > last used 3.00347333 seconds ago (Net::HTTP::Persistent::Error)
> > > ```
> > > 
> > > 
> > > 该错误看起来像链接超时。
> > 
> > 
> > 我认为节点链接是正常的，并且数据库也已正常插入。这是日志
> > ![图片](https://user-images.githubusercontent.com/20334885/88761807-79683100-d1a2-11ea-95be-92d62433e664.png)
> > 稍后，将节点部署到同一服务器上，并观察问题是否会再次出现
> 
> 好

It's really great. Replace the local node. It's been running for a day and a night without being disconnected.
